//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UchebnayaPractika.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int IdNote { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public System.DateTime CreationDate { get; set; }
        public int IdUser { get; set; }
    
        public virtual User User { get; set; }
    }
}
