//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stroyka.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int idMaterial { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public int idUnit { get; set; }
        public double price { get; set; }
        public double discountMax { get; set; }
        public int idManufacturer { get; set; }
        public int idSupplier { get; set; }
        public int idCategory { get; set; }
        public double discount { get; set; }
        public int stock { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public double discountPrice { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual MaterialCategory MaterialCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
