//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stroyka.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string firstName { get; set; }
        public string secondName { get; set; }
        public string middleName { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int idRole { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public System.DateTime birthday { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
