//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Material()
        {
            this.MaterialSupplier = new HashSet<MaterialSupplier>();
        }
    
        public int idMaterial { get; set; }
        public string name { get; set; }
        public int idMaterialType { get; set; }
        public string image { get; set; }
        public int price { get; set; }
        public int numberInStock { get; set; }
        public int minimalNumber { get; set; }
        public int numberInPack { get; set; }
        public int idUnitName { get; set; }
    
        public virtual MaterialType MaterialType { get; set; }
        public virtual UnitName UnitName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupplier> MaterialSupplier { get; set; }
    }
}
