//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session2
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int idUser { get; set; }
        public string firstName { get; set; }
        public string fathersName { get; set; }
        public string lastName { get; set; }
        public System.DateTime birthday { get; set; }
        public string passportData { get; set; }
        public string bankProperties { get; set; }
        public string healthProblems { get; set; }
        public Nullable<bool> hasFamily { get; set; }
    }
}
