//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursovayaWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basket
    {
        public int idBasket { get; set; }
        public int idOrder { get; set; }
        public int idOrderItem { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
